name: Push to Wiki

on:
  push:
    branches:
      - "wiki"

concurrency:
  group: "wiki-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  publish:
    name: Publish Wiki
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: wiki
          fetch-depth: 0

      - uses: OrlovM/Wiki-Action@v1
        with:
          path: '.'
          token: ${{ secrets.GITHUB_TOKEN }}
